general:
  buildTool: 'npm'
  gitHttpsCredentialsId: 'pccibuild_private_github_wdf_user_token'
steps:
  cloudFoundryDeploy:
    deployTool: 'cf_native'
    cloudFoundry:
      org: 'CLOUDCIDEV_cicddev'
      space: 'd036667'
      credentialsId: 'testKayCF'
      loginParameters: '--origin cicddev-platform'
